

	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Lamp', 'Fancy table lamp', 500, '2015-12-22','test_items/lamp.jpg', 'good', 'ClarkKent@gmail.com','AlbertCamus@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Acer PC', 'All new powerful computer',800 , '2015-12-28','test_items/acercomputer.jpg', 'Excellent', 'JosephStailin@gmail.com','OliverQueen@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Apple Computer', 'If you love apple this is the desktop for you', 1130, '2016-01-02','test_items/appledesktop.png', 'Excellent', 'JamesBond@gmail.com','TylerDurden@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Beagle Bone Black', 'A small powerful linux computer', 49, '2015-10-12','test_items/bbb.JPG', 'Poor' ,'AaronSwartz@gmail.com','BruceWayne@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Motorcycle', 'If you are trying to go fast this will do the trick', 3000, '2015-12-01','test_items/blackmotorcycle.jpg','good', 'SpongebobSquarepants@gmail.com','ClarkKent@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Rolex Watch', 'A luxery to own such a flashy watch', 10000, '2015-08-24','test_items/blackrolex.jpg','excellent', 'FyodorDostoyvesky@gmail.com','AlanTuring@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Decorative Plate', 'A plate to hang above your fireplace at home to display for all your guests', 45, '2015-09-12','test_items/blueplate.jpg','poor', 'JohnSteinbeck@gmail.com','MarkTwain@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Ceiling Fan', 'If your home is getting too hot try out this great fan', 30, '2015-10-31','test_items/ceilingfan.jpg', 'poor','ErnestHemingway@gmail.com','OscarWilde@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Celtic Sword', 'If the ancient Celtics intrest you here is a genuine sword', 300, '2016-03-12','test_items/celticsword.jpg','average', 'GeorgeOrwell@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Compass', 'Are you lost? here is a compass', 25, '2016-01-01','test_items/compass.jpg', 'excellent', 'JamesBond@gmail.com','ChuckPalahniuk@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Converse', 'New shoes just for you', 45, '2015-02-04','test_items/converse.png', 'poor', 'TonyStark@gmail.com','KevinMitnick@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Cookies', 'Are you hungry? Here are some cookies', 10, '2015-06-01','test_items/cookies.jpg','excellent', 'BruceBanner@gmail.com','AlanTuring@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Cows Statue', 'Here is the next level to show your love for cows', 40, '2015-12-01','test_items/cow.jpg','average', 'BobbyFlay@gmail.com','ErnestHemingway@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Cowboy Hat', 'For our cowboy enthusiasts ', 35, '2015-10-23','test_items/cowboyhat.jpg','poor', 'OscarWilde@gmail.com','HarperLee@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Desk', 'A nice place to get some work done', 50, '2015-12-04','test_items/desk.png','average', 'TylerDurden@gmail.com','AaronSwartz@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Dyson Fan', 'Are you scared of blades... well this is a bladeless fan', 50, '2015-02-28','test_items/dysonfan.jpg','good', 'ClarkKent@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Elaphant Statue', 'A simple statue of a elephant', 25, '2015-08-20','test_items/elephant.jpg','good', 'AlbertCamus@gmail.com','MarkTwain@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Fan', 'Trying to stay cool? this might help', 35, '2015-12-05','test_items/fan.jpg','average', 'JamesBond@gmail.com','OscarWilde@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Flannel Shirt', 'If it is starting to get cold this might hlep', 20, '2015-12-01','test_items/flannel.jpg','average', 'JosephStalin@gmail.com','BruceWayne@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Golf Clubs', 'Whether you are starting or have been doing it for years, you can never have too many golf clubs', 150, '2015-10-13','test_items/golfclubset.jpg','average', 'TonyStark@gmail.com','ClarkKent@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('High Heels', 'For that special night', 45, '2015-07-13','test_items/highheels.jpg', 'excellent','OliverQueen@gmail.com','BruceBanner@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Jacket', 'For the chilly months', 35, '2015-11-23','test_items/jacket.jpg','poor', 'PeterParker@gmail.com','JamesBond@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Japanese Fan', 'For the most stylistic person', 12, '2015-12-01','test_items/japanesefan.jpg','excellent', 'KevinMitnick@gmail.com','JohnSteinbeck@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Eletric Piano', 'For the ones who do not have much space', 230, '2015-10-12','test_items/keyboardpiano.jpg','good', 'ClarkKent@gmail.com','JosephStalin@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Tiffany Lamp', 'A very decorative lamp', 140, '2015-12-01','test_items/lamptiffany.jpg','excellent', 'MarkTwain@gmail.com','TylerDurden@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Shoes', 'maroon shoes', 30, '2015-03-12','test_items/maroonvans.jpg', 'average','BarryAllan@gmail.com','BruceWayne@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Master Shield', 'You need to defeat Ganon', 1000000, '2015-09-12','test_items/mastershield.jpg','poor', 'PeterParker@gmail.com','TonyStark@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Master Sword', 'The almighty sword', 5000000, '2015-08-10','test_items/mastersword.png', 'poor','MarkTwain@gmail.com','AaronSwartz@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Dress shoes', 'For the fancy night', 50, '2015-12-01','test_items/mensdressshoes.jpg', 'excellent', 'OliverQueen@gmail.com','JoshephStalin@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Mercedes', 'The car to go with you new dress shoes', 23000, '2015-03-12','test_items/mercedes.jpg', 'average','ChuckPalahniuk@gmail.com','JamesBOnd@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Mirror', 'How else are you suppose to know if you look good?', 25, '2015-06-12','test_items/mirror.png', 'good', 'ClarkKent@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Motorcycle', 'Trying to go fast?', 3000, '2015-01-24','test_items/moto.jpg', 'good', 'PeterParker@gmail.com','JamesBond@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Pants', 'New pants', 24, '2015-09-23','test_items/pants.jpg', 'average', 'ErnestHemmingway@gmail.com','OscarWilde@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Paper', 'Paper for your new printer', 25, '2015-09-23','test_items/paper.jpg','excellent', 'BobbyFlay@gmail.com','OscarWilde@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Shoes', 'Some pink vans', 25, '2015-12-01','test_items/pinkvans.jpg', 'excellent','FyodorDoste@gmail.com','HarperLee@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Plare', 'A fancy plate', 24, '2015-04-18','test_items/plate.jpg', 'good', 'AlanTuring@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Playing Cards', 'If you are trying to go to vegas, how about some practice first?', 15, '2015-06-17','test_items/playingcards.jpeg','excellent', 'BruceWayne@gmail.com','KevinMitnick@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Motorcycle', 'This is the bike for you if going fast is not fast enough', 10000, '2015-08-15','test_items/porchemotorcycle.jpg', 'good','AaronSwartz@gmail.com','JamesBond@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Printer', 'The best printer money can buy', 60, '2015-03-29','test_items/printer.jpg', 'good','HarperLee@gmail.com','BruceBanner@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Poker Chips', 'For you playing cards you just bought ;)', 15, '2015-06-17','test_items/pokerchips.jpeg','poor', 'TylerDurden@gmail.com','ClarkKent@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Play Station 1', 'Game Console', 50, '2015-03-15','test_items/ps1.jpg', 'poor','BruceBanner@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Play Station 2', 'Game Console', 75, '2015-02-23','test_items/ps2.jpeg', 'average','OliverQueen@gmail.com','JosephStalin@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Play Station 3', 'Game Console', 125, '2015-06-19','test_items/ps3.jpg', 'good','ClarkKent@gmail.com','PeterParker@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Play Station 4', 'Game Console', 200, '2015-05-19','test_items/ps4.jpeg', 'excellent','BruceBanner@gmail.com','TonyStark@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Car', 'A fancy car to go fast', 20000, '2015-12-03','test_items/purplecar.jpg', 'good','JamesBond@gmail.com','AaronSwartz@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Rolex Watch', 'For the one who is interested in the finer things', 14000, '2015-02-23','test_items/rolex.jpg','good', 'KevenMitnick@gmail.com','AlanTuring@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Safe', 'Lock away all your valuables', 50, '2015-01-01','test_items/safe.jpg', 'good','AlbertCamus@gmail.com','FyodorDostevesky@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Shirt', 'A cool shirt', 20, '2015-01-28','test_items/shirt.jpeg', 'good', 'TylerDurdent@gmail.com','GeorgeOrwell@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Sponge Job Shirt', 'Do you love spongebob', 15, '2015-09-28','test_items/spndgebobshirt.jpg','excellent', 'JohnSteinBeck@gmail.com','ChuckPalahniuk@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Shoes', 'Vans that show the night sky', 23, '2015-03-30','test_items/starvans.jpg', 'good','HarperLee@gmail.com','MarkTwain@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Sunglasses', 'For sunny California', 20, '2015-10-08','test_items/sunglasses.jpg', 'good','OscarWilde@gmail.com','ErnestHemmin@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Motorcycle', 'The fastes bike out there', 2800, '2015-10-31','test_items/sv650.jpg','excellent', 'FrankButt@gmail.com','EdgarAllanPoe@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Sword', 'Want a sword?', 30, '2015-04-04','test_items/sword.jpg', 'poor','AlbertEinstein@gmail.com','FranklinRoosevelt@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Tiffany Lamp', 'A fancy lamp', 300, '2015-01-03','test_items/tiffanylamp.jpg', 'excellent','TheoRoosevelt@gmail.com','BobbyFlay@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Tiffany Vase', 'A fancy vase', 200, '2015-05-18','test_items/tiffanyvase.jpg', 'excellent','ErnestHemingway@gmail.com','OscarWilde@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Toad', 'Mario lovers', 30, '2015-12-01','test_items/toad.jpeg', 'goood', 'MarkTwain@gmail.com','HarperLee@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Tower Computer', 'The best computer out there', 500, '2015-08-23','test_items/towercomputer.png','excellent', 'GeorgeOrwell@gmail.com','AlbertEinstein@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Television', 'A big tv for your house', 200, '2015-04-12','test_items/tv.png', 'good','AlbertEinstein@gmail.com','EdgarAllanPoe@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Type Writer', 'For the vintage feeling', 150, '2015-12-01','test_items/typewriter.jpg','excellent', 'FranklinRoosevelt@gmail.com','TylerDurden@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('USA Flag', 'For the patriotic members', 80, '2015-07-04','test_items/usaflag.jpg', 'good','FyodorDoste@gmail.com','FrankButt@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Shoes', 'For the patriotic shoe wearer', 30, '2015-06-23','test_items/usavans.jpg', 'poor','TonyStark@gmail.com','JamesBond@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Vase', 'For flowers', 25, '2015-12-08','test_items/vase.jpg', 'good','AlbertEinstein@gmail.com','KevinMitnick@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Viking Sword', 'For the viking studyers', 200, '2015-10-12','test_items/vikingsword.png','average', 'TonyStark@gmail.com','TylerDurden@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Motorcycle', 'A fast bike', 3000, '2015-10-03','test_items/vulcan.jpg','average', 'TheodoreRoosevelt@gmail.com','BruceBanner@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Car', 'A white car', 3000, '2015-01-01','test_items/whitecare.jpg', 'average','ChuckPalahniuk@gmail.com','AaronSwartz@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Jacket', 'For when it gets cold', 35, '2015-02-05','test_items/womanjacket.jpeg', 'good','JamesBond@gmail.com','TonyStark@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Xbox', 'The orginal Xbox', 50, '2015-12-01','test_items/xbox.jpg', 'poor', 'OscarWilde@gmail.com','AlbertEinstein@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Xbox 360', 'Game Console', 100, '2015-10-09','test_items/xbox360.jpg', 'average', 'FrankButt@gmail.com','EdgarAllanPoe@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Xbox One', 'Game Console', 200, '2015-01-01','test_items/xboxone.png', 'excellent','FrankRoosevelt@gmail.com','GeorgeOrwell@gmail.com')^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ('Piano', 'For the piano players', 3000, '2015-03-24','test_items/yamahapiano.jpeg','excellent','JamesBond@gmail.com', 'KevinMitnick@gmail.com')^
