	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Ojen', 'test', 'ojen@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Frank', 'Butt', 'FrankButt@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Edgar Allan', 'Poe', 'EdgarAllanPoe@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Albert', 'Einstein', 'AlbertEinstein@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Franklin', 'Roosevelt', 'FrankRoosevelt@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Theodore', 'Roosevelt', 'TheoRoosevelt@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Bobby', 'Flay', 'BobbyFlay@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Ernest', 'Hemmingway', 'ErnestHemmin@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Oscar', 'Wilde', 'OscarWilde@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Mark', 'Twain', 'MarkTwain@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Harper', 'Lee', 'HarperLee@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Chuck', 'Palahniuk', 'ChuckPalahniuk@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('John', 'Steinbeck', 'JohnSteinbeck@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('George', 'Orwell', 'GeorgeOrwll@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Tyler', 'Durden', 'TylerDurden@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Fyodor', 'Dostoyevsky', 'FyodorDostoyevsky', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Albert', 'Camus', 'AlberCamus@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Alan', 'Turing', 'AlanTuring@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Kevin', 'Mitnick', 'KevinMitnick@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Aaron', 'Swartz', 'AaronSwartz@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('James', 'Bond', 'JamesBond@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Spongebob', 'Squarepants', 'Spongebobs@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Tony', 'Stark', 'TonyStark@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Bruce', 'Banner', 'BruceBanner@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Peter', 'Parker', 'PeterParker@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Clark', 'Kent', 'ClarkKent@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Bruce', 'Wayne', 'BruceWayne@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Joseph', 'Stalin', 'JosephStalin@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Oliver', 'Queen', 'OliverQueen@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Barry', 'Allen', 'BarryAllen@gmail.com', 'pass', 'T')^
	INSERT INTO users ( first_name, last_name, email, password, is_seller ) values ('Lex', 'Luther', 'LexLuther@gmail.com', 'pass', 'T')^
